---
# Default values for admission-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

registry: docker.io
org: networkservicemesh
tag: v0.2.0
pullPolicy: IfNotPresent
