---
apiVersion: extensions/v1beta1
kind: Deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io: "true"
        networkservicemesh.io/app: "nse"
    spec:
      containers:
        - name: icmp-responder-nse\
          securityContext:
            privileged: true
          image: networkservicemesh/vppagent-icmp-responder-nse:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              nsm.ligato.io/socket: 1
metadata:
  name: vppagent-icmp-responder-nse
  namespace: default
